### ISSUE TITLE
输出内容时候，有希望能输出的是 vue 模版文件吗？

### ISSUE THREAD

**Issue by yeyuguo** [rxwater/rxeditor#10]
输出内容时候，有希望能输出的是 vue 模版文件吗？

**Comment by rxwater** [comment]
这个希望不大，如果要做到这样，需要依赖具体的VUE库，内核逻辑要修改很多。这个项目，我目前暂停了。
我现在在用React做另外一个项目，基于mui，本来是想可以生成react 代码，类似原理。后来改变策略，直接生称前端。这样就可以不需要前端代码，拖放就可以完成基本业务前端，感兴趣的化，可以关注一下。https://github.com/rxwater/rxdrag

**Comment by adyuebanwan** [comment]
> 输出内容时候，有希望能输出的是 vue 模版文件吗？
要不你试试 www.magicalcoder.com的布局器？可以实现你说的导出vue的代码风格，至于生成文件 就是把字符串存成文件而已
